#!/bin/bash
options=(
  style=round
  width=8.0
  hidpi=on
  active_color="glow(0xffc4a7e7)"  # rose pine iris with glow
  inactive_color=0xff524f67        # rose pine highlight high
)
borders "${options[@]}"
