version: 2
root-markers:
  - .git/

tools:
  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint'
    lint-formats:
      - '%f:%l %m'

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  eslint: &eslint
    lint-command: 'eslint_d -f unix --stdin --stdin-filename ${INPUT}'
    lint-formats:
      - "%f:%l:%c: %m"
    lint-ignore-exit-code: true
    lint-stdin: true
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json

  prettier: &prettier
    format-command: 'prettierd ${INPUT}'
    format-stdin: true

  json-jq: &json-jq
    lint-command: 'jq .'

languages:
  markdown:
    - <<: *prettier

  yaml:
    - <<: *yaml-yamllint

  dockerfile:
    - <<: *dockerfile-hadolint

  sh:
    - <<: *sh-shellcheck

  javascript:
    - <<: *eslint
    - <<: *prettier

  typescript:
    - <<: *eslint
    - <<: *prettier

  typescriptreact:
    - <<: *eslint
    - <<: *prettier

  html:
    - <<: *prettier

  css:
    - <<: *prettier

  json:
    - <<: *json-jq
