## COLORSCHEME: gruvbox dark hard
set-option -g status "on"

# default statusbar color
set-option -g status-style bg=#1d2021,fg=#ebdbb2

# default window title colors
set-window-option -g window-status-style bg=#3c3836,fg=#ebdbb2

# default window with an activity alert
set-window-option -g window-status-activity-style bg=#1d2021,fg=#ebdbb2

# active window title colors
set-window-option -g window-status-current-style bg=#fabd2f,fg=#1d2021

# pane border
set-option -g pane-active-border-style fg=#504945
set-option -g pane-border-style fg=#3c3836

# message infos
set-option -g message-style bg=#3c3836,fg=#ebdbb2

# writing commands inactive
set-option -g message-command-style bg=#3c3836,fg=#ebdbb2

# pane number display
set-option -g display-panes-colour #1d2021
set-option -g display-panes-active-colour #fabd2f

# clock
set-window-option -g clock-mode-colour #8ec07c

# bell
set-window-option -g window-status-bell-style bg=#fb4934,fg=#ebdbb2

## Theme settings
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[bg=#fabd2f,fg=#1d2021] #S #[bg=#1d2021,fg=#fabd2f,nobold,noitalics,nounderscore]"
set-option -g status-right "#[bg=#1d2021,fg=#3c3836 nobold, nounderscore, noitalics]#[bg=#3c3836,fg=#ebdbb2] %Y-%m-%d #[bg=#3c3836,fg=#1d2021] #[bg=#3c3836,fg=#ebdbb2]%H:%M #[bg=#3c3836,fg=#fabd2f,nobold,noitalics,nounderscore]#[bg=#fabd2f,fg=#1d2021] #h "

set-window-option -g window-status-current-format "#[bg=#fabd2f,fg=#1d2021,nobold,noitalics,nounderscore]#[bg=#fabd2f,fg=#1d2021] #I #[bg=#fabd2f,fg=#1d2021,bold] #W#{?window_zoomed_flag, ◎,} #[bg=#1d2021,fg=#fabd2f,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#3c3836,fg=#1d2021,noitalics]#[bg=#3c3836,fg=#ebdbb2] #I #[bg=#3c3836,fg=#1d2021]#[bg=#3c3836,fg=#ebdbb2] #W #[bg=#1d2021,fg=#3c3836,noitalics]"

# vim: set ft=tmux tw=0 nowrap:
