## COLORSCHEME: gruvbox light medium
set-option -g status "on"

# default statusbar color
set-option -g status-style bg=#fbf1c7,fg=#3c3836

# default window title colors
set-window-option -g window-status-style bg=#ebdbb2,fg=#3c3836

# default window with an activity alert
set-window-option -g window-status-activity-style bg=#fbf1c7,fg=#3c3836

# active window title colors
set-window-option -g window-status-current-style bg=#b57614,fg=#fbf1c7

# pane border
set-option -g pane-active-border-style fg=#d5c4a1
set-option -g pane-border-style fg=#ebdbb2

# message infos
set-option -g message-style bg=#ebdbb2,fg=#3c3836

# writing commands inactive
set-option -g message-command-style bg=#ebdbb2,fg=#3c3836

# pane number display
set-option -g display-panes-colour #fbf1c7
set-option -g display-panes-active-colour #b57614

# clock
set-window-option -g clock-mode-colour #427b58

# bell
set-window-option -g window-status-bell-style bg=#9d0006,fg=#fbf1c7

## Theme settings
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[bg=#b57614,fg=#fbf1c7] #S #[bg=#fbf1c7,fg=#b57614,nobold,noitalics,nounderscore]"
set-option -g status-right "#[bg=#fbf1c7,fg=#ebdbb2 nobold, nounderscore, noitalics]#[bg=#ebdbb2,fg=#3c3836] %Y-%m-%d #[bg=#ebdbb2,fg=#fbf1c7] #[bg=#ebdbb2,fg=#3c3836]%H:%M #[bg=#ebdbb2,fg=#b57614,nobold,noitalics,nounderscore]#[bg=#b57614,fg=#fbf1c7] #h "

set-window-option -g window-status-current-format "#[bg=#b57614,fg=#fbf1c7,nobold,noitalics,nounderscore]#[bg=#b57614,fg=#fbf1c7] #I #[bg=#b57614,fg=#fbf1c7,bold] #W#{?window_zoomed_flag, ◎,} #[bg=#fbf1c7,fg=#b57614,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#ebdbb2,fg=#fbf1c7,noitalics]#[bg=#ebdbb2,fg=#3c3836] #I #[bg=#ebdbb2,fg=#fbf1c7]#[bg=#ebdbb2,fg=#3c3836] #W #[bg=#fbf1c7,fg=#ebdbb2,noitalics]"

# vim: set ft=tmux tw=0 nowrap:
