## COLORSCHEME: kanagawa lotus
set-option -g status "on"

# default statusbar color
set-option -g status-style bg=#f2ecbc,fg=#545464

# default window title colors
set-window-option -g window-status-style bg=#e5ddb0,fg=#545464

# default window with an activity alert
set-window-option -g window-status-activity-style bg=#f2ecbc,fg=#545464

# active window title colors
set-window-option -g window-status-current-style bg=#77713f,fg=#f2ecbc

# pane border
set-option -g pane-active-border-style fg=#d9d0a7
set-option -g pane-border-style fg=#e5ddb0

# message infos
set-option -g message-style bg=#e5ddb0,fg=#545464

# writing commands inactive
set-option -g message-command-style bg=#e5ddb0,fg=#545464

# pane number display
set-option -g display-panes-colour #f2ecbc
set-option -g display-panes-active-colour #77713f

# clock
set-window-option -g clock-mode-colour #597b75

# bell
set-window-option -g window-status-bell-style bg=#c84053,fg=#f2ecbc

## Theme settings
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[bg=#77713f,fg=#f2ecbc] #S #[bg=#f2ecbc,fg=#77713f,nobold,noitalics,nounderscore]"
set-option -g status-right "#[bg=#f2ecbc,fg=#e5ddb0 nobold, nounderscore, noitalics]#[bg=#e5ddb0,fg=#545464] %Y-%m-%d #[bg=#e5ddb0,fg=#f2ecbc] #[bg=#e5ddb0,fg=#545464]%H:%M #[bg=#e5ddb0,fg=#77713f,nobold,noitalics,nounderscore]#[bg=#77713f,fg=#f2ecbc] #h "

set-window-option -g window-status-current-format "#[bg=#77713f,fg=#f2ecbc,nobold,noitalics,nounderscore]#[bg=#77713f,fg=#f2ecbc] #I #[bg=#77713f,fg=#f2ecbc,bold] #W#{?window_zoomed_flag, ◎,} #[bg=#f2ecbc,fg=#77713f,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#e5ddb0,fg=#f2ecbc,noitalics]#[bg=#e5ddb0,fg=#545464] #I #[bg=#e5ddb0,fg=#f2ecbc]#[bg=#e5ddb0,fg=#545464] #W #[bg=#f2ecbc,fg=#e5ddb0,noitalics]"

# vim: set ft=tmux tw=0 nowrap:
