## COLORSCHEME: rose-pine dawn warm (light)
set-option -g status "on"

# default statusbar color
set-option -g status-style bg=#f2e9e1,fg=#575279

# default window title colors
set-window-option -g window-status-style bg=#ede4dc,fg=#575279

# default window with an activity alert
set-window-option -g window-status-activity-style bg=#f2e9e1,fg=#575279

# active window title colors
set-window-option -g window-status-current-style bg=#d7827e,fg=#f2e9e1

# pane border
set-option -g pane-active-border-style fg=#dfdad9
set-option -g pane-border-style fg=#ede4dc

# message infos
set-option -g message-style bg=#ede4dc,fg=#575279

# writing commands inactive
set-option -g message-command-style bg=#ede4dc,fg=#575279

# pane number display
set-option -g display-panes-colour #f2e9e1
set-option -g display-panes-active-colour #d7827e

# clock
set-window-option -g clock-mode-colour #56949f

# bell
set-window-option -g window-status-bell-style bg=#b4637a,fg=#f2e9e1

## Theme settings
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[bg=#d7827e,fg=#f2e9e1] #S #[bg=#f2e9e1,fg=#d7827e,nobold,noitalics,nounderscore]"
set-option -g status-right "#[bg=#f2e9e1,fg=#ede4dc nobold, nounderscore, noitalics]#[bg=#ede4dc,fg=#575279] %Y-%m-%d #[bg=#ede4dc,fg=#f2e9e1] #[bg=#ede4dc,fg=#575279]%H:%M #[bg=#ede4dc,fg=#d7827e,nobold,noitalics,nounderscore]#[bg=#d7827e,fg=#f2e9e1] #h "

set-window-option -g window-status-current-format "#[bg=#d7827e,fg=#f2e9e1,nobold,noitalics,nounderscore]#[bg=#d7827e,fg=#f2e9e1] #I #[bg=#d7827e,fg=#f2e9e1,bold] #W#{?window_zoomed_flag, ◎,} #[bg=#f2e9e1,fg=#d7827e,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#ede4dc,fg=#f2e9e1,noitalics]#[bg=#ede4dc,fg=#575279] #I #[bg=#ede4dc,fg=#f2e9e1]#[bg=#ede4dc,fg=#575279] #W #[bg=#f2e9e1,fg=#ede4dc,noitalics]"

# vim: set ft=tmux tw=0 nowrap:
