## COLORSCHEME: rose-pine dawn (light)
set-option -g status "on"

# default statusbar color
set-option -g status-style bg=#faf4ed,fg=#575279

# default window title colors
set-window-option -g window-status-style bg=#b4637a,fg=#575279

# default window with an activity alert
set-window-option -g window-status-activity-style bg=#faf4ed,fg=#575279

# active window title colors
set-window-option -g window-status-current-style bg=#b4637a,fg=#faf4ed

# pane border
set-option -g pane-active-border-style fg=#dfdad9
set-option -g pane-border-style fg=#f2e9e1

# message infos
set-option -g message-style bg=#faf4ed,fg=#575279

# writing commands inactive
set-option -g message-command-style bg=#f2e9e1,fg=#575279

# pane number display
set-option -g display-panes-colour #faf4ed
set-option -g display-panes-active-colour #d7827e

# clock
set-window-option -g clock-mode-colour #56949f

# bell
set-window-option -g window-status-bell-style bg=#b4637a,fg=#575279

## Theme settings mixed with colors (unfortunately, but there is no cleaner way)
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[bg=#d7827e,fg=#575279] #S #[bg=#faf4ed,fg=#d7827e,nobold,noitalics,nounderscore]"
set-option -g status-right "#[bg=#faf4ed,fg=#f2e9e1 nobold, nounderscore, noitalics]#[bg=#f2e9e1,fg=#d7827e] %Y-%m-%d #[bg=#f2e9e1,fg=#faf4ed] #[bg=#f2e9e1,fg=#d7827e]%H:%M #[bg=#f2e9e1,fg=#d7827e,nobold,noitalics,nounderscore]#[bg=#d7827e,fg=#faf4ed] #h "

set-window-option -g window-status-current-format "#[bg=#d7827e,fg=#faf4ed,nobold,noitalics,nounderscore]#[bg=#d7827e,fg=#faf4ed] #I #[bg=#d7827e,fg=#f2e9e1,bold] #W#{?window_zoomed_flag, ◎,} #[bg=#faf4ed,fg=#d7827e,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#f2e9e1,fg=#faf4ed,noitalics]#[bg=#f2e9e1,fg=#d7827e] #I #[bg=#f2e9e1,fg=#faf4ed]#[bg=#f2e9e1,fg=#d7827e] #W #[bg=#faf4ed,fg=#f2e9e1,noitalics]"

# vim: set ft=tmux tw=0 nowrap:
